### ISSUE TITLE
countByEnumeratingWithState:objects:count: crashes if managed context changes while enumerated

### ISSUE THREAD

**Issue by cristik** [martydill/ios-queryable#7]
The method in discussion executes a fetch request (via its `toArray`) each time the runtime asks for a batch of objects to enumerate through. And if the managed object contents change between fetch requests, it generates a crash as the `toArray` contents are not the same between invocations.

**Comment by cristik** [comment]
Note - I reproduced the crash only on iOS9, probably because the batch size of the enumeration was reduced since iOS8.

**Comment by martydill** [comment]
Hey, thanks for the bug report! You are right, fast enumeration support could definitely use some optimizations.
I've been trying to reproduce the crash on iOS 9, by adding/removing various numbers of items on the managed object context during an enumeration, but haven't been able to actually make it crash. Do you happen to have some sample code that reproduces it?

**Comment by cristiankocza** [comment]
Unfortunately I can't easily extract the relevant code from the project.

Caching the `toArray` result per [enumeration state](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSFastEnumeration_protocol/#//apple_ref/doc/c_ref/NSFastEnumerationState) should fix the issue, however this approach needs to circumvent ARC's retain/release calls as NSFastEnumerationState is a simple struct.

**Comment by martydill** [comment]
I've just pushed a fix for this. Hopefully it resolves your issues!

**Comment by cristiankocza-sv** [comment]
Thanks, will check the updated behaviour it and get back to you.
